language: python

matrix:
  fast_finish: true

  include:
    - python: "3.6"
      env: PURE_TESTS=1
#   - python: "3.6"
#      env: BROWSER_TESTS=1
#      addons:
#        firefox: latest-esr

install:
  - pip install -e .
  - pip install -r testing/requirements.txt

before_install:
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - if [[ "$BROWSER_TESTS" == 1 ]]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;

      wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz;
      mkdir geckodriver;
      tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver;
      export PATH=$PATH:$PWD/geckodriver;
    fi

script:
  - if [[ "$BROWSER_TESTS" == 1 ]]; then
      python -c "import splinter; print(splinter);";
      python splinter_test.py;
    fi

  #- which gnupg
  #- pip install pexpect
  #- python testing/test_wizard.py

  - if [[ "$PURE_TESTS" == 1 ]]; then
      pytest --doctest-modules pyggybank;
    fi
